services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: mariadb:11.3
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: laravel
      MARIADB_USER: user
      MARIADB_PASSWORD: user
      MARIADB_ROOT_PASSWORD:
    volumes:
      - ./data/db:/var/lib/mysql
